namespace LogShark.Shared
{
    public enum LogType
    {
        Apache,
        BackgrounderCpp,
        BackgrounderJava,
        ClusterController,
        ControlLogsJava,
        CrashPackageLog,
        CrashPackageManifest,
        DataserverCpp,
        DataserverJava,
        Filestore,
        Hyper,
        NetstatLinux,
        NetstatWindows,
        PostgresCsv,
        Prep,
        flowprocessorCpp,
        flowprocessorJava,
        ProtocolServer,
        SearchServer,
        Tabadmin,
        TabadminAgentJava,
        TabadminControllerJava,
        TabsvcYml,
        VizdataJava,
        VizdataCpp,
        VizportalCpp,
        VizportalJava,
        VizqlserverCpp,
        VizqlDesktop,
        UnknownLogTypeForErrors,
        WorkgroupYml,
        Zookeeper
    }
}