# Site settings
title: Logshark
email: github@tableau.com

description: Tableau log file analysis utility.
repository: d45/tableau.github.io
baseurl: "/Logshark"
permalinks: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
github: [metadata]
markdown: kramdown
highlighter: rouge

